### ISSUE TITLE
Platform for program

### ISSUE THREAD

**Issue by Omaiwei-kun** [grimmdaniel/personality-trait-prediction#1]
Can it also run on Google Colab?

**Comment by grimmdaniel** [comment]
Yes, you can rut it on Colab as well, but in that case make sure you can upload the dataset(~25GB) to google drive, and then connect your drive with Colab. Otherwise, by just uploading the dataset directly into Colab, it would take a very long time, and if you don't have a paid account, every time when the runtime resets itself (for example you turn on GPU support, or you just become inactive for some hours) you will loose every uploaded data, and you need to start over again.
