### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by Omaiwei-kun** [grimmdaniel/personality-trait-prediction#2]
Hi @grimmdaniel, may i know why when i try to getting train, validation and testing set. I encountered error T**ypeError: expected str, bytes or os.PathLike object, not list** . I am using jupyter notebook to run the code. tq

**Comment by grimmdaniel** [comment]
Please provide a more detailed error log, or code snippet.

**Comment by Omaiwei-kun** [comment]
Hi @grimmdaniel , somehow I managed to solve the issue by including 

**!pip3 install ffmpeg-python
!pip3 install librosa
!pip3 install matplotlib
!pip3 install numba**

However may i know what is ur machine's spec as when I try to train the model, it is very time consuming, and my train sample is 188, not 6000 like u share

![image](https://user-images.githubusercontent.com/65478357/105660076-31ce2200-5f05-11eb-9f70-57248daf06a2.png)

**Comment by grimmdaniel** [comment]
My configuration is: i7 8700, 32GB RAM, RTX 2060super VGA. For the slow training time I think the problem is that you are training on CPU and not GPU. If you cannot manage to train on GPU, I recommend running this code in Colab.

In the notebook there is a part where I dumped the preprocessed data, and after that I restarted the notebook kernel, and then only loaded the preprocessed files, to speed up development, because I was running out memory. If you follow the code cell by cell, when you execute this cell:
print(len(train_set_data))
print(len(validation_set_data))
print(len(test_set_data))
you should get 6000 2000 2000. If you not get this, there is a problem with your dataset.

**Comment by Omaiwei-kun** [comment]
![image](https://user-images.githubusercontent.com/65478357/105797518-19c0d600-5fcb-11eb-93bf-0c369ddb2d05.png)

The data I got also same 6000,2000,2000 . but the problem still remains, I also have try using colab but the there is eror "Your session crashed after using all available RAM" . Have u encounter it using when using colab?
